<table class="ts-table is-fitted">
    <tbody>
        <tr>
            <td><strong>__FILE__</strong></td>
            <td><?=htmlentities(__FILE__)?></td>
        </tr>

        <tr>
            <td><strong>Router::uri()</strong></td>
            <td><?=htmlentities(Router::uri())?></td>
        </tr>
        <tr>
            <td><strong>Router::local()</strong></td>
            <td><?=htmlentities(Router::local())?></td>
        </tr>
        <tr>
            <td><strong>Router::path()</strong></td>
            <td><?=htmlentities(Router::path())?></td>
        </tr>
        <tr>
            <td><strong>Router::root()</strong></td>
            <td><?=htmlentities(Router::root())?></td>
        </tr>
        <tr>
            <td><strong>Router::$args</strong></td>
            <td><?=htmlentities(json_encode(Router::$args))?></td>
        </tr>
        <tr>
            <td><strong>Router::parmsStr()</strong></td>
            <td><?=htmlentities(Router::parmsStr())?></td>
        </tr>
    </tbody>
</table>