version: "3"

name: ${APP}

volumes:
  db-data:

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
      #- MARIADB_USER=user
      #- MARIADB_PASSWORD=password
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      default:
        ipv4_address: ${SUBNET}.0.2

  app:
    image: ${IMAGE}
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TZ: Asia/Taipei
    volumes:
      - ../app/:/usr/share/nginx/html
      - ../nginx:/etc/nginx
    networks:
      default:
        ipv4_address: ${SUBNET}.0.3
      
networks:
  default:
    name: ${NET_NAME}
    driver: bridge
    external: true